# Generated by Django 2.0.8 on 2018-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videoFile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
