# Generated by Django 2.0.8 on 2018-10-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181012_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('audiofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='audios/', verbose_name=''),
        ),
    ]
